Setup-magento uses composer instead of archive.\nUserScripts-function rewritten to use scripts in order and named nn-scriptname.sh \nAdded delegated/cached to volumes.\n

diff --git a/bin/setup-magento b/bin/setup-magento
--- a/bin/setup-magento
+++ b/bin/setup-magento
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-VERSION=2.4.0
 SAMPLEDATA=1
 EXT=""
 QUIET=0
@@ -13,15 +12,17 @@ function usage()
 {
   echo -e "Usage:"
   echo -e ""
-  echo -e "$ bash setup-magento.bash" 
+  echo -e "$ bash setup-magento" 
   echo -e ""
   echo -e "Arguments:"
   echo -e "--version"
   echo -e "  Your preferred version of Magento 2."
-  echo -e "  bash setup-magento.bash --version=2.4.1"
+  echo -e "  bash setup-magento --version=2.4.1"
+  echo -e "  or:"
+  echo -e "  bash setup-magento --version=latest"
   echo -e "--sample-data"
   echo -e "  Setup Magento 2 with sample data."
-  echo -e "  bash setup-magento.bash --version=2.4.1 --sample-data=1"
+  echo -e "  bash setup-magento --version=2.4.1 --sample-data=1"
   echo -e "--quiet or -q"
   echo -e "  No prompts"
   echo -e "-h or --help"
@@ -202,14 +203,15 @@ function preinstall()
   echo -e "  \033[1mTIMEZONE\033[0m = ${TIMEZONE}\n"
 
   if [ $QUIET == 1 ]; then
-    download
+    #download
+    composerSetup
   else
     echo -e "\033[1m"
     read -p "Is this correct [Y/n]? " CHOICE
     echo -e "\033[0m"
     case "$CHOICE" in 
         n|N ) echo -e "Please edit the env-file and re-run the installer."; return;;
-        * ) download;;
+        * ) composerSetup #download;;
     esac
   fi
 
@@ -219,16 +221,16 @@ function preinstall()
 function copyfiles()
 {
 
-  if ! docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d; then
+  if ! docker-compose -f docker-compose.yml up -d; then
     echo -e "\033[1m\033[31mERROR: Failed to start Docker services\033[0m"
     exit 1
   fi
   sleep 5
 
-  echo -e "\033[1mCopying files from host to container...\033[0m"
+  echo -e "\033[1mCopying files from container to host...\033[0m"
 
   PHPFPM_CONTAINER=$(docker-compose ps -q phpfpm | awk '{print $1}')
-  docker cp ./src/./ "${PHPFPM_CONTAINER}":/var/www/html
+  docker cp "${PHPFPM_CONTAINER}":/var/www/html ./src/./
 
   if ! docker cp ./src/./ "${PHPFPM_CONTAINER}":/var/www/html; then
     echo -e "\033[1m\033[31mERROR: Copying of files failed!\033[0m"
@@ -247,6 +249,11 @@ function copyfiles()
 
 function composerSetup()
 {
+  if ! docker-compose -f docker-compose.yml up -d; then
+    echo -e "\033[1m\033[31mERROR: Failed to start Docker services\033[0m"
+    exit 1
+  fi
+
   if ! docker-compose exec -T phpfpm composer global config http-basic.repo.magento.com "$PUBLIC_KEY" "$PRIVATE_KEY"; then
     echo -e "\033[1m\033[31mERROR: Couldn't set keys for repo.magento.com!\033[0m"
     exit
@@ -254,14 +261,28 @@ function composerSetup()
     echo -e "Keys for repo.magento.com set..."
   fi
 
+  docker-compose exec -T phpfpm bash -c "composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=${VERSION} /var/www/html"
+
   echo -e "\033[1mYou will see the following from Composer:\033[0m"
   echo -e "  Package hirak/prestissimo is abandoned... "
   echo -e "\033[1mWhich is totally fine since we're still forced to use Composer v1.\033[0m"
   echo -e "\033[1mYou can safely remove this once the Magento 2 modules are updated to play nice with Composer v2\033[0m"
   
+  if ! docker-compose exec -T phpfpm bash -c "mkdir -p var/composer_home && cp /var/www/.composer/auth.json var/composer_home/auth.json"; then
+    echo -e "\033[1m\033[31mERROR: Couldn't set keys for repo.magento.com in var/composer_home!\033[0m"
+    exit
+  else
+    echo -e "Keys for repo.magento.com set in var/composer_home..."
+  fi
+
   docker-compose exec -T phpfpm composer global require hirak/prestissimo
 
-  echo -e "\033[1mUpdating Composer modules. This will take a while...\033[0m"
+  if [[ $SAMPLEDATA == 1 ]]; then
+    echo -e "\033[1mInstalling sample data. Go get a nice cup of coffee...\033[0m"
+    docker-compose exec -T phpfpm bash -c "bin/magento sampledata:deploy"
+  fi
+
+  echo -e "\033[1mUpdating Composer modules. Go get a kanelbulle...\033[0m"
   docker-compose exec -T phpfpm composer update
 
   installMagento
@@ -269,13 +290,14 @@ function composerSetup()
 
 function installMagento()
 {
+  
   docker-compose exec -T phpfpm bin/magento setup:install \
     --db-host="$MYSQL_HOST" \
     --db-name="$MYSQL_DATABASE" \
     --db-user="$MYSQL_USER" \
     --db-password="$MYSQL_PASSWORD" \
-    --base-url=https://"$BASE_URL"/ \
-    --base-url-secure=https://"$BASE_URL"/ \
+    --base-url=https://"${BASE_URL}"/ \
+    --base-url-secure=https://"${BASE_URL}"/ \
     --backend-frontname="$ADMIN_URL" \
     --admin-firstname=John \
     --admin-lastname=Doe \
@@ -303,46 +325,13 @@ function installMagento()
     --search-engine=elasticsearch7 \
     --elasticsearch-host=elasticsearch \
     --use-rewrites=1
-
+    
   postInstall
 }
 
 function postInstall()
 {
-  echo -e "\033[1m De-bloating the install... \033[0m"
-  docker-compose exec -T phpfpm bin/magento module:disable \
-    Amazon_Core \
-    Amazon_Login \
-    Amazon_Payment \
-    Dotdigitalgroup_Chat \
-    Dotdigitalgroup_Email \
-    Magento_AdobeIms \
-    Magento_AdobeImsApi \
-    Magento_AdobeStockAdminUi \
-    Magento_AdobeStockAsset \
-    Magento_AdobeStockAssetApi \
-    Magento_AdobeStockClient \
-    Magento_AdobeStockClientApi \
-    Magento_AdobeStockImage \
-    Magento_AdobeStockImageAdminUi \
-    Magento_AdobeStockImageApi \
-    Magento_CardinalCommerce \
-    Magento_Dhl \
-    Magento_Elasticsearch6 \
-    Magento_Fedex \
-    Magento_NewRelicReporting \
-    Magento_Ups \
-    Magento_Usps \
-    Magento_Weee \
-    Magento_WeeeGraphQl \
-    PayPal_Braintree \
-    PayPal_BraintreeGraphQl \
-    Temando_ShippingRemover \
-    Vertex_AddressValidation \
-    Vertex_Tax \
-    Yotpo_Yotpo
-
-#   Vertex_AddressValidationApi \
+  copyfiles
 
   echo -e "\033[1mSetting admin session lifetime to 1 year... \033[0m"
   docker-compose exec -T phpfpm bin/magento config:set admin/security/session_lifetime 31536000
@@ -378,12 +367,13 @@ function postInstall()
 
 function userScripts()
 {
-  USERFILES=$(find ./conf.d -type f -name '*.sh' 2> /dev/null | wc -l)
-  #echo $USERFILES
-  if [[ $USERFILES -gt 0 ]]; then
+  USERFILES=$(find -Es ./conf.d -type f -iregex '.*/[0-9]{2}.*sh$' -print | sort)
+  FILECOUNT=$(find -Es ./conf.d -type f -iregex '.*/[0-9]{2}.*sh$' -print | wc -l)
+
+  if [[ $FILECOUNT -gt 0 ]]; then
     echo -e "\033[1mRunning scripts in conf.d... \033[0m"
-    for f in ./conf.d/*.sh; do
-      bash "$f" -H || break
+    for s in ${USERFILES};do
+      bash "$s" -H || break
     done
   else
     echo -e "\033[1mNo scripts found in conf.d. \033[0m"
@@ -412,7 +402,7 @@ while [ "$1" != "" ]; do
       QUIET=1
       ;;
     --debug)
-      DEBUG=1
+      set -x
       ;;
     *)
       echo -e "ERROR: unknown parameter \"$PARAM\""
@@ -420,11 +410,11 @@ while [ "$1" != "" ]; do
       exitcomposerSetup
       ;;
   esac
+  if ! [[ $VERSION ]]; then
+    getLatestVersion
+  fi
   shift
 done
-
-echo $VERSION
-exit
 
 if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
 then
